name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # ou master selon ton dépôt

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Connexion à DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build de l’image Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-site:latest .

      - name: Push de l’image sur DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon-site:latest

